#!/bin/bash

## Before pipewire instaallation
# output_string="$(amixer set 'Master' toggle | grep Mono | grep -v channels)"

## After pipewire instaallation
output_string="$(amixer set 'Master' toggle | grep Left | grep -v Right)"

muted=0
notify_string='Unmuted'

if [[ $output_string == *"[off]"* ]]; then
	notify_string='Muted'
fi

notify-send $notify_string





