#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width        0 # 4
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating focus=on


## Autostart
xset -b &
xbacklight -set 10 &
xsetroot -cursor_name left_ptr &
sxhkd &
xrdb ~/.Xresources
urxvtd -q &
# feh --bg-scale --randomize ~/.wallpapers/*
feh --bg-scale ~/.wallpapers/wallhaven-x6p3y3_1920x1200.png
picom -b &
mpd --no-daemon &
# ~/.config/polybar/colorblocks/./launch.sh &
pipewire &
boff &
woff &
mpd --no-daemon &

notify-send "Welcome to VOID"
