#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating focus=on


## Autostart
xset -b &
xbacklight -set 10 &
xsetroot -cursor_name left_ptr &
sxhkd &
xrdb ~/.Xresources
urxvtd -q &
feh --bg-scale --randomize ~/.wallpapers/*
# feh --bg-scale ~/.wallpapers/11.jpg

notify-send "Welcome to VOID"
