#!/bin/bash
bat="$(cat /sys/class/power_supply/BAT0/capacity)"
charging_status="$(cat /sys/class/power_supply/BAT0/status)"

notification="Battery: $bat% $charging_status"

if [[ $bat -le 25 ]]; then
	notify-send -u critical "$notification"
else
	notify-send "$notification"
fi
